### ISSUE TITLE
Cannot remove element from XML array

### ISSUE THREAD

**Issue by ed-gallagher** [clbanning/mxj#74]
I'm trying to manipulate an XML file similar to the following example (simplified):
```
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="http://example.com" catalog-id="my-catalog">
    <product product-id="a">
        <online-flag>false</online-flag>
        <available-flag>true</available-flag>
    </product>

    <product product-id="b">
        <online-flag>true</online-flag>
        <available-flag>true</available-flag>
    </product>
</catalog>
```

Essentially I want to remove any `<product>` where `<online-flag>` is set to false and output a new XML file reflecting those changes. Here's the code I'm using to try to accomplish that:

```
package main

import (
	"log"
	"os"
	"strconv"

	"github.com/clbanning/mxj"
)

func check(e error) {
	if e != nil {
		panic(e)
	}
}

func main() {
	catalogXML, err := os.Open("catalog_example.xml")
	check(err)
	defer catalogXML.Close()

	mv, err := mxj.NewMapXmlReader(catalogXML)
	check(err)

	item, err := mv.ValuesForPath("catalog.product")
	check(err)

	total := 0
	online := 0

	for i, v := range item {
		data := v.(map[string]interface{})

		if data["online-flag"] == "true" {
			online++
		} else {
			path := "catalog.product[" + strconv.Itoa(i) + "]"
			log.Println("removing", path)
			getpid, err := mv.ValueForPath(path)
			check(err)
			log.Println(getpid)

			err = mv.Remove(path)
			check(err)
		}

		total++
	}

	catalogXMLReduced, err := os.Create("catalog_reduced.xml")
	check(err)
	defer catalogXMLReduced.Close()

	err = mv.XmlWriter(catalogXMLReduced)
	check(err)

	log.Println(online, "online /", total, "total")
}
```

Here's the output:

```
2020/09/01 00:43:33 removing catalog.product[0]
2020/09/01 00:43:33 map[-product-id:a available-flag:true online-flag:false]
panic: prevValueByPath: didn't find path – product[0]

goroutine 1 [running]:
main.check(...)
        main.go:13
main.main()
        main.go:44 +0x630
```

It would appear as though the path notation I'm using to reference the specific product key is supported in ValueForPath(), but throws an error when used with Remove().

**Comment by clbanning** [comment]
Try this.  Though you've still got capture the leading <?...> processing instruction(s) and write them to output file first.

```
package main

import (
	"fmt"

	"github.com/clbanning/mxj"
)

func main() {

	data := []byte(`
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="http://example.com" catalog-id="my-catalog">
    <product product-id="a">
        <online-flag>false</online-flag>
        <available-flag>true</available-flag>
    </product>

    <product product-id="b">
        <online-flag>true</online-flag>
        <available-flag>true</available-flag>
    </product>
</catalog>`)

	m, err := mxj.NewMapXml(data)
	if err != nil {
		fmt.Println("err:", err)
		return
	}

	mm := map[string]interface{}(m)
	val, ok := mm["catalog"].(map[string]interface{})["product"]
	if ok != true {
		fmt.Println("catalog.product err:", ok)
		return
	}

        // Here I'm assuming that val is of type []interface{}. 
        // If there's only 1 product then val will be type interface{}.
        // Probably need a switch val.(type) block to handle the two possible cases.

	var newlist []interface{}
	for _, p := range val.([]interface{}) {
		v, ok := p.(map[string]interface{})["online-flag"]
		if ok != true {
			fmt.Println("no online-flag")
			continue
		}
		if v.(string) == "false" {
			continue
		}
		newlist = append(newlist, p)
	}
	mm["catalog"].(map[string]interface{})["product"] = newlist

	x, err := m.XmlIndent("", "   ")
	if err != nil {
		fmt.Println("XmlIndent err:", err)
		return
	}
	fmt.Println(string(x))
}
```

**Comment by clbanning** [comment]
The ValueForPath method is an old method that doesn't understand accessing []interface{} list members.  Probably something I should spend some time on; though this is the first issue regarding this.  

Should actually have Remove() method support list elements for your use-case, as well.

**Comment by clbanning** [comment]
An alternative, but more opaque, version is:

```
package main

import (
	"fmt"

	"github.com/clbanning/mxj"
)

func main() {

	data := []byte(`
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="http://example.com" catalog-id="my-catalog">
    <product product-id="a">
        <online-flag>false</online-flag>
        <available-flag>true</available-flag>
    </product>

    <product product-id="b">
        <online-flag>true</online-flag>
        <available-flag>true</available-flag>
    </product>
</catalog>`)

	m, err := mxj.NewMapXml(data)
	if err != nil {
		fmt.Println("err:", err)
		return
	}

	vals, err := m.ValuesForPath("catalog.product")
	if err != nil {
		fmt.Println("ValuesForPath err:", err)
		return
	}

	var newlist []interface{}
	for _, p := range vals {
		v, ok := p.(map[string]interface{})["online-flag"]
		if ok != true {
			fmt.Println("no online-flag")
			continue
		}
		if v.(string) == "false" {
			continue
		}
		newlist = append(newlist, p)
	}
	if err := m.SetValueForPath(newlist, "catalog.product"); err != nil {
		fmt.Println("SetValueForPath err:", err)
		return
	}

	x, err := m.XmlIndent("", "   ")
	if err != nil {
		fmt.Println("XmlIndent err:", err)
		return
	}
	fmt.Println(string(x))
}
```

**Comment by ed-gallagher** [comment]
@clbanning This appears to accomplish exactly what I needed -- thanks for the comprehensive example!

**Comment by clbanning** [comment]
Please note that the processing instructions are being stripped.  If you need them as part of the output, then you should strip them off before processing XML doc.
```
    i := bytes.Index(data, []byte("<cat"))
    // write out data[:1]

   data = data[i:]
   // now process the XML doc
```
